# Applying Logistic Regression Model Workflow

## Import relevant modules

In [1]:
import pandas
import math

## Store intercept, column names, coefficients and output column name variables

In [2]:
intercept =.92428029
column_names =['height_B', 'reach_A', 'won_B', 'lost_A', 'lost_B', 'drawn_A',
       'drawn_B', 'kos_B', 'age_diff', 'kd_diff_B', 'stance_A_southpaw',
       'stance_B_southpaw']
coefficients =[-0.026907131594570408, 0.02965530670846954, 0.07293576251518107, -0.09885390749492504, 0.10424850798319237, -0.028024100297096764, -0.03992409120896212, -0.0639861490523247, -0.022415465347209652, -0.031312745466804244, 0.015331346599411426, 0.015331346599411426]
output_y = 'result'

## Read in test data

In [3]:
subset_path = "/Users/danielcorcoran/PycharmProjects/daniels_mac_proj/jupyter_notebooks/logistic_regression/boxing_last_x_records.csv"
data = pandas.read_csv(subset_path)

## Calculate the predicted outcome, using the inputs from the model

In [4]:
partial_total = intercept
ypred = "model_output_prediction"
match_flag_name = "model_prediction_true_or_false"

for index in range(len(column_names)):
    partial_total = partial_total + data[column_names[index]] * coefficients[index]

full_formula = 1 / (1 + math.exp(1)**-(partial_total))

data = pandas.concat(
    [data,
     full_formula.ge(.5).replace([True, False], [1, 0]).rename(ypred)],
    axis=1)

old_result_list = data[output_y].tolist()
new_result_list = data[ypred].tolist()

total_possible = len(old_result_list)

## Create column, if predicted value matches the actual value

In [5]:
match_list = []

for n in range(len(old_result_list)):
    if old_result_list[n] == new_result_list[n]:
        match_list.append(1)
    else:
        match_list.append(0)

data = pandas.concat(
    [data, pandas.Series(match_list).rename(match_flag_name)], axis=1)

## Checking subset of final data

In [6]:
data.head(10)

,Unnamed: 0,age_A,age_B,height_A,height_B,reach_A,reach_B,weight_A,weight_B,won_A,...,age_diff,height_diff,reach_diff,weight_diff,kd_diff_A,kd_diff_B,stance_A_southpaw,stance_B_southpaw,model_output_prediction,model_prediction_true_or_false
0,2228,30.0,43.0,191.0,192.0,198.0,198.0,235.0,224.0,24,...,-13.0,-1.0,0.0,11.0,22,41,0,0,1,1
1,2229,40.0,32.0,192.0,188.0,198.0,196.0,231.0,229.0,46,...,8.0,4.0,2.0,2.0,40,23,0,0,1,0
2,2230,39.0,30.0,192.0,191.0,198.0,206.0,237.0,235.0,46,...,9.0,1.0,-8.0,2.0,41,28,0,0,1,0
3,2231,38.0,35.0,192.0,185.0,198.0,196.0,230.0,239.0,45,...,3.0,7.0,2.0,-9.0,41,19,0,0,1,0
4,2232,38.0,31.0,192.0,193.0,198.0,203.0,228.0,215.0,43,...,7.0,-1.0,-5.0,13.0,39,26,0,0,1,1
5,2233,33.0,31.0,192.0,193.0,198.0,216.0,236.0,236.0,33,...,2.0,-1.0,-18.0,0.0,30,20,0,0,1,1
6,2234,29.0,25.0,192.0,194.0,198.0,211.0,217.0,222.0,26,...,4.0,-2.0,-13.0,-5.0,23,13,0,0,1,1
7,2235,28.0,27.0,192.0,190.0,198.0,201.0,227.0,244.0,23,...,1.0,2.0,-3.0,-17.0,21,21,0,0,1,1
8,2236,26.0,26.0,192.0,191.0,198.0,196.0,217.0,216.0,18,...,0.0,1.0,2.0,1.0,17,24,0,0,1,0
9,2237,26.0,23.0,160.0,173.0,160.0,173.0,112.0,112.0,32,...,3.0,-13.0,-13.0,0.0,31,13,1,1,1,1

In [7]:
data[[output_y, ypred, match_flag_name]]

     result  model_output_prediction  model_prediction_true_or_false
0         1                        1                               1
1         0                        1                               0
2         0                        1                               0
3         0                        1                               0
4         1                        1                               1
5         1                        1                               1
6         1                        1                               1
7         1                        1                               1
8         0                        1                               0
9         1                        1                               1
10        0                        1                               0
11        1                        1                               1
12        1                        1                               1
13        1                        1                               1
14        1                        1                               1
15        1                        1                               1
16        0                        1                               0
17        0                        1                               0
18        1                        1                               1
19        1                        1                               1
20        1                        1                               1
21        0                        1                               0
22        1                        1                               1
23        1                        1                               1
24        1                        1                               1
25        1                        1                               1
26        1                        1                               1
27        1                        1                               1
28        1                        1                               1
29        1                        1                               1
..      ...                      ...                             ...
470       0                        1                               0
471       1                        1                               1
472       1                        1                               1
473       1                        1                               1
474       1                        1                               1
475       1                        1                               1
476       0                        1                               0
477       1                        1                               1
478       1                        1                               1
479       1                        1                               1
480       1                        1                               1
481       1                        1                               1
482       1                        1                               1
483       1                        1                               1
484       0                        1                               0
485       0                        1                               0
486       1                        1                               1
487       1                        1                               1
488       1                        1                               1
489       0                        1                               0
490       0                        1                               0
491       1                        1                               1
492       1                        1                               1
493       1                        1                               1
494       1                        1                               1
495       1                        1                               1
496       0                        1                               0
497       1                        1                               1
498       1                        1                               1
499       1                        1                               1

[500 rows x 3 columns]

## Calculate the accuracy of the model against the test subset

In [8]:
accuracy = "{:.2%}".format(data[match_flag_name].sum()/data.shape[0])
print("Accuracy of model against test subset: ",accuracy)

Accuracy of model against test subset:  88.00%

## Export data (optional)

In [9]:
data.to_csv("boxing_data_tested_against_model.csv")